### ISSUE TITLE
BUG: Unable to delete an ecoverse

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/server#1002]
**Describe the bug**
attempting to delete an ecoverse via the api returns an error:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ad6711c2-b368-48dc-ace4-704bcf202c9e)

This is as the ecoverse contains a challenge, which needs to be reflected in the db scripts.

**Comment by Comoque1** [comment]
Similar behavior is experienced, when intend to delete opportunity containing project.

 ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f4354f7e-cdcd-4209-bcf6-7bfcc5869149)

**Comment by techsmyth** [comment]
Addressed in commit 703c508a347c19910f08aa8562db0ccdc0b1f433

**Comment by Comoque1** [comment]
The ecoverse, still cannot be deleted, but receiving a meaningful message.

@techsmyth, could you please, confirm, that this is the expected behavior?
 ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f2f24f74-f76b-406a-bc01-8b618f59c11a)

**Comment by techsmyth** [comment]
Yes this is intended, for now we prevent deletion of ecoverses with contained challenges
